### ISSUE TITLE
Locale: change ignoreRequests work strategy

### ISSUE THREAD

**Issue by g-rodigy** [yiisoft/yii-middleware#112]
### What steps will reproduce the problem?
````php
// definition
Yiisoft\Yii\Middleware\Locale::class => [
    '__construct()' => [
        'supportedLocales' => ['en' => 'en-US', 'uk' => 'uk-UA'],
        'ignoredRequestUrlPatterns' => [
            '/api/**', 
            '/debug**'
        ],
    ],
    'withDefaultLocale()' => ['en'],
],
````
Example url: site.com/api/users
Current: when request has't locale will be placed default locale

If no locale check for `isRequestIgnored` not started.
https://github.com/yiisoft/yii-middleware/blob/8c001b1c9926883cfe767aa0f5bd602ace89e5e7/src/Locale.php#L107

### What is the expected result?
site.com/api/users

### What do you get instead?
site.com/en/api/users

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.1
| PHP version      | 8.0
| Operating system |

**Comment by arogachev** [comment]
Fixed in #113.
