### ISSUE TITLE
How to dynamic set ipRanges value in IpFilter?

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii-middleware#119]
How to dynamic set ipRanges value in IpFilter?

**Comment by vjik** [comment]
It is middleware. Why need to change IP ranges dynamic?

**Comment by xepozz** [comment]
```php
class Middleware {
  //...

  public function process($req, $handler) {
    $data = $this->storage->getData(); // db, file, dynamic, a/b
    return (new IpFilter(...))->process($req, $handler);
  }
}
```

**Comment by hiscaler** [comment]
> It is middleware. Why need to change IP ranges dynamic?

Like use for API endpoint for diff clients.
Check special client is from Specified IP

**Comment by vjik** [comment]
Creating your own middleware with usage `IpFilter`, as suggest @xepozz [above ](https://github.com/yiisoft/yii-middleware/issues/119#issuecomment-2166828832), is good solution.

**Comment by hiscaler** [comment]
@xepozz @vjik Thanks. is ok!
