### ISSUE TITLE
Split `TrustedHostsNetworkResolver` into separate classes

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/yii-middleware#43]

**Comment by samdark** [comment]
What's the idea? What do you want to extrace?

**Comment by rustamwin** [comment]
The `TrustedHostsNetworkResolver` class is currently too large and difficult to maintain. I would suggest extracting classes that each have a `TrustedHostsNetworkResolver::DATA_KEY_*` property (see [`BasicNetworkResolver`](https://github.com/yiisoft/yii-middleware/blob/9f3ec8cf430a3790f12e8296ddaee52cb65fbe5b/src/BasicNetworkResolver.php) for example). WDYT?

**Comment by samdark** [comment]
Do you mean multiple middleware?

**Comment by rustamwin** [comment]
Yes.

**Comment by samdark** [comment]
From the user standpoint that's going to be too busy in the configs.
