### ISSUE TITLE
`Locale` - using short name vs full name

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii-middleware#90]
https://github.com/yiisoft/yii-middleware/blob/cea436a46f6b937de6dddce015326655210b18ab/src/Locale.php#L130-L131

**Comment by samdark** [comment]
Full name is needed in translator since when formating intl is taking it into account.

**Comment by samdark** [comment]
https://github.com/yiisoft/i18n/blob/master/src/Locale.php

```php
$locale = new Locale($fullName);
$short = $locale->language();
```

Language could be easily obtained from the full name.
