### ISSUE TITLE
`Locale` always redirect to URL without locale for GET requests

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-middleware#96]
For example. GET `http://127.0.0.1:30080/ru/blog/` redirects to `http://127.0.0.1:30080/blog/`.

![image](https://github.com/yiisoft/yii-middleware/assets/525501/cfab8a6a-7a6f-4a82-bec9-80c2ba72e590)

**Comment by samdark** [comment]
This should be logical behavior:

<img width="1092" alt="image" src="https://github.com/yiisoft/yii-middleware/assets/47294/286559e7-8e05-43fd-aa3d-7cbb79974cdd">

**Comment by samdark** [comment]
Simplified it a bit:

<img width="1344" alt="image" src="https://github.com/yiisoft/yii-middleware/assets/47294/c961800c-9aac-4196-beb0-921c1cbfbe01">

**Comment by samdark** [comment]
Fixed issues with default locale:

<img width="1299" alt="image" src="https://github.com/yiisoft/yii-middleware/assets/47294/e8ef6d62-d3da-4114-a643-01a753862c6a">

**Comment by samdark** [comment]
Fixed issues with default locale:

<img width="1293" alt="image" src="https://github.com/yiisoft/yii-middleware/assets/47294/cd425fc0-abc6-44f5-b8e4-e097fa2d76d7">

**Comment by samdark** [comment]
<img width="948" alt="image" src="https://github.com/yiisoft/yii-middleware/assets/47294/84eb746e-4dcf-487e-bf74-75e039ad5427">
